---
abstract: 'Browser integration framework inspired by Capybara'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Temp: 0
  Test::Exception: 0
  Test::Fake::HTTPD: 0.03
  Test::Mock::Guard: 0
  Test::More: 0.98
  Test::UseAllModules: 0
  URI::QueryParam: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Brownie
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Load: 0
  File::Slurp: 0
  HTML::Selector::XPath: 0
  HTML::TreeBuilder::XPath: 0
  MIME::Base64: 0
  Plack::Runner: 0
  Scalar::Util: 1.14
  Selenium::Remote::Driver: 0
  Selenium::Server: 0
  Sub::Install: 0
  Test::TCP: 0
  URI: 0
  WWW::Mechanize: 0
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/masaki/Brownie.git
version: 0.09
